FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_ENV
ARG VITE_API_URL

ENV VITE_ENV=$VITE_ENV \
    VITE_API_URL=$VITE_API_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 2407

CMD ["serve", "-s", "dist", "-l", "2407"]
